config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :matchups
  resources :players
  resources :tournaments

  root 'pages#home'

  get 'pages/home'

  get 'pages/dashboard'

  get 'pages/tournament'
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  belongs_to :user
  has_many :players,    foreign_key: :tournament_id
  has_many :matchups,   foreign_key: :tournament_id

end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]

  # GET /tournaments
  # GET /tournaments.json
  def index
    @tournaments = Tournament.all
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
    @user_id = @tournament.user_id
    @players = @tournament.players
    @matchups = @tournament.matchups
  end

  # GET /tournaments/new
  def new
    @tournament = current_user.tournaments.new
  end

  # GET /tournaments/1/edit
  def edit
    @user_id = @tournament.user_id
    @players = @tournament.players
    @matchups = @tournament.matchups
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    @tournament = current_user.tournaments.new(tournament_params)

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to @tournament, notice: 'Tournament was successfully created.' }
        format.json { render :show, status: :created, location: @tournament }
      else
        format.html { render :new }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1
  # PATCH/PUT /tournaments/1.json
  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
        format.json { render :show, status: :ok, location: @tournament }
      else
        format.html { render :edit }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_url, notice: 'Tournament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tournament_params
      params.require(:tournament).permit(:name, :user_id)
    end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.erb
<%= form_with(model: tournament, local: true) do |form| %>
  <% if tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
      <% tournament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :tournament_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tournaments/edit.html.erb
<h1>Editing Tournament</h1>

<%= render 'form', tournament: @tournament %>

<%= render 'form', tournament: @tournament %>

<br />
<form>
  <label>Enter player name
    <input type="text" placeholder="Player A">
  </label>
</form>

<button type="button" class="button success">Create player</button>

<table>
  <thead>
    <tr>
      <th>Seat #</th>
      <th>Icon</th>
      <th>Player name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.id %></td>
        <td><%= player.icon_img %></td>
        <td><%= player.name %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="space-around">
  <div class="third">
      <button type="button" class="button expand">Add 8 players</button>
  </div>
  <div class="two-thirds">
    <button type="button" class="button expand">Randomize seating</button>
  </div>
</div>

<br />
<button type="button" class="button large warning">Create Round 1 pairings</button>

<h3>Round No. 1</h3>

<table>
  <thead>
    <tr>
      <th>Round #</th>
      <th>Match #</th>
      <th colspan="2">Player A</th>
      <th></th>
      <th colspan="2">Player B</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matchups.each do |matchup| %>
      <tr>
        <td><%= matchup.round_id %></td>
        <td><%= matchup.id %></td>
        <td><em>PLAYER A</em> </td>
        <td><strong>vs</strong></td>
        <td><em>PLAYER B</em></td>        
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Current Standings</h3>

<table>
  <thead>
    <tr>
      <th>Rank</th>
      <th colspan="3">Player name</th>
      <th colspan="4">Score</th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.id %></td>
        <td><%= player.icon_img %> <%= player.name %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />
<%= link_to 'Show', @tournament %> |
<%= link_to 'Back', tournaments_path %>

app/views/tournaments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tournaments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tournaments.each do |tournament| %>
      <tr>
        <td><%= tournament.name %></td>
        <td><%= link_to 'Show', tournament %></td>
        <td><%= link_to 'Edit', edit_tournament_path(tournament) %></td>
        <td><%= link_to 'Destroy', tournament, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tournament', new_tournament_path %>

app/views/tournaments/new.html.erb
<h2>New Tournament</h2>

<%= render 'form', tournament: @tournament %>

<br/>
<h3>Players</h3>

<form action="">
  <label>
    Select # of players
    <input type="number" min="8" max="32" placeholder="8">
  </label>
</form>

<br />
<%= link_to 'Back', tournaments_path %>

app/views/tournaments/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Viewing Tournament No. <%= @tournament.id %> </h2>

<p>
  <strong>Name:</strong> <%= @tournament.name %>
</p>

<p>
  <strong>Created by:</strong> User No. <%= @user_id %> 
</p>

<h3>Players</h3>

<table>
  <thead>
    <tr>
      <th>Seat #</th>
      <th>Icon</th>
      <th>Player name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.id %></td>
        <td><%= player.icon_img %></td>
        <td><%= player.name %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Round No. 1</h3>

<table>
  <thead>
    <tr>
      <th>Round #</th>
      <th>Match #</th>
      <th colspan="2">Player A</th>
      <th></th>
      <th colspan="2">Player B</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matchups.each do |matchup| %>
      <tr>
        <td><%= matchup.round_number %></td>
        <td><%= matchup.id %></td>
        <td><em>PLAYER A</em> </td>
        <td><strong>vs</strong></td>
        <td><em>PLAYER B</em></td>        

      </tr>
    <% end %>
  </tbody>
</table>

<h3>Round No. 2</h3>

<table>
  <thead>
    <tr>
      <th>Round #</th>
      <th>Match #</th>
      <th colspan="2">Player A</th>
      <th></th>
      <th colspan="2">Player B</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matchups.each do |matchup| %>
      <tr>
        <td><%= matchup.round_number %></td>
        <td><%= matchup.id %></td>
        <td><em>PLAYER A</em> </td>
        <td><strong>vs</strong></td>
        <td><em>PLAYER B</em></td>        
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Round No. 3</h3>

<table>
  <thead>
    <tr>
      <th>Round #</th>
      <th>Match #</th>
      <th colspan="2">Player A</th>
      <th></th>
      <th colspan="2">Player B</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matchups.each do |matchup| %>
      <tr>
        <td><%= matchup.round_number %></td>
        <td><%= matchup.id %></td>
        <td><em>PLAYER A</em> </td>
        <td><strong>vs</strong></td>
        <td><em>PLAYER B</em></td>        
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Final Standings</h3>

<table>
  <thead>
    <tr>
      <th>Rank</th>
      <th colspan="3">Player name</th>
      <th colspan="4">Score</th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.id %></td>
        <td><%= player.icon_img %> <%= player.name %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />
<%= link_to 'Edit Tournament', edit_tournament_path(@tournament) %> |
<%= link_to 'Back', tournaments_path %>