config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :matchups
  resources :players
  resources :tournaments

  root 'pages#home'

  get 'pages/home'

  get 'pages/dashboard'

  get 'pages/tournament'
end

app/models/matchup.rb
class Matchup < ApplicationRecord
  belongs_to :tournament 
  has_many :matchup_players
  has_many :players, through: :matchup_players
end

app/controllers/matchups_controller.rb
class MatchupsController < ApplicationController
  before_action :set_matchup, only: [:show, :edit, :update, :destroy]

  # GET /matchups
  # GET /matchups.json
  def index
    @matchups = Matchup.all
  end

  # GET /matchups/1
  # GET /matchups/1.json
  def show
  end

  # GET /matchups/new
  def new
    @matchup = Matchup.new
  end

  # GET /matchups/1/edit
  def edit
  end

  # POST /matchups
  # POST /matchups.json
  def create
    @matchup = Matchup.new(matchup_params)

    respond_to do |format|
      if @matchup.save
        format.html { redirect_to @matchup, notice: 'Matchup was successfully created.' }
        format.json { render :show, status: :created, location: @matchup }
      else
        format.html { render :new }
        format.json { render json: @matchup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matchups/1
  # PATCH/PUT /matchups/1.json
  def update
    respond_to do |format|
      if @matchup.update(matchup_params)
        format.html { redirect_to @matchup, notice: 'Matchup was successfully updated.' }
        format.json { render :show, status: :ok, location: @matchup }
      else
        format.html { render :edit }
        format.json { render json: @matchup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matchups/1
  # DELETE /matchups/1.json
  def destroy
    @matchup.destroy
    respond_to do |format|
      format.html { redirect_to matchups_url, notice: 'Matchup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_matchup
      @matchup = Matchup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def matchup_params
      params.require(:matchup).permit(:round_number)
    end
end

app/helpers/matchups_helper.rb
module MatchupsHelper
end

app/views/matchups/_form.html.erb
<%= simple_form_for(@matchup) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :round_number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/matchups/edit.html.erb
<h1>Editing Matchup</h1>

<%= render 'form', matchup: @matchup %>

<%= link_to 'Show', @matchup %> |
<%= link_to 'Back', matchups_path %>

app/views/matchups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Matchups</h1>

<table>
  <thead>
    <tr>
      <th>Round number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matchups.each do |matchup| %>
      <tr>
        <td><%= matchup.round_number %></td>
        <td><%= link_to 'Show', matchup %></td>
        <td><%= link_to 'Edit', edit_matchup_path(matchup) %></td>
        <td><%= link_to 'Destroy', matchup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Matchup', new_matchup_path %>

app/views/matchups/new.html.erb
<h1>New Matchup</h1>

<%= render 'form', matchup: @matchup %>

<%= link_to 'Back', matchups_path %>

app/views/matchups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Round number:</strong>
  <%= @matchup.round_number %>
</p>

<%= link_to 'Edit', edit_matchup_path(@matchup) %> |
<%= link_to 'Back', matchups_path %>